# This file only configures the container for development, DOCKERFILE is used for deploment.
# If you intent do commit changes here, make sure to also make the same changes in the DOCKERFILE

services:
  node-red:
    image: nodered/node-red:4.1.4-22 # Defult node-red image, newest version per 28.01.2026 (make sure version is the same in DOCKERFILE)
    dns: # Set custom DNS servers for the container in case of network issues (EAI_AGAIN error)
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "1880:1880" # Dafult ports for a node red project
    volumes: # syncing local files to container files
      - ./data:/data
    entrypoint: /bin/sh -c "cd /data && npm install && npm prune && cd /usr/src/node-red && npm start -- --userDir /data" # Auto-install and sync packages from package.json on startup