# This file only configures the container for development, DOCKERFILE is used for deploment.
# If you intent do commit changes here, make sure to also make the same changes in the DOCKERFILE

services:
  node-red:
    build: . # run docker build in the current directory, using the Dockerfile
    # Set custom DNS servers for the container in case of network issues (EAI_AGAIN error)
    #dns:
    #  - 8.8.8.8
    #  - 8.8.4.4
    ports:
      - "1880:1880" # Default ports for a node red project
    volumes: # syncing local files to container files
      - ./data:/data
    entrypoint: /bin/sh -c "cd /data && npm install && npm prune && cd /usr/src/node-red && npm start -- --userDir /data" # Auto-install and sync packages from package.json on startup
