# This file only configures the container for development, DOCKERFILE is used for deploment.
# If you intent do commit changes here, make sure to also make the same changes in the DOCKERFILE

services:
  node-red:
    image: nodered/node-red:4.1.4-22
    user: root
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
      - node_modules:/data/node_modules
    entrypoint: /bin/sh -c "cd /data && npm install && npm prune && cd /usr/src/node-red && npm start -- --userDir /data"

volumes:
  node_modules:
